name: Update end date for bangumi

on:
  schedule:
    - cron: '15 3 3 4 *'
    # - cron: '0 4 1 * *''

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Get current time
        id: current-time
        uses: srfrnk/current-time@master
        with:
          format: X

      - name: Set branch name
        id: branch-name
        run: echo "::set-output name=result::$BRANCH_NAME"
        env:
          BRANCH_NAME: "update-end-${{ steps.current-time.outputs.formattedTime }}"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Create a new branch
        run: git checkout -b ${{ steps.branch-name.outputs.result }}

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Run bdh to update end date
        run: npx bangumi-data-helper end

      - name: Commit
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v4.1.1
        with:
          commit_message: Update end date
          branch: ${{ steps.branch-name.outputs.result }}

      - name: Create pull request
        if: steps.commit.outputs.changes_detected == true
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ steps.branch-name.outputs.result }}
          pr_title: "Auto end date update"
          pr_reviewer: "wxt2005"
          pr_assignee: "wxt2005"
          pr_label: "action"
          github_token: ${{ secrets.GITHUB_TOKEN }}
