name: Update end date for bangumi

on:
  schedule:
    - cron: '27 6 3 4 *'
    # - cron: '0 4 1 * *''

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Get current time
        id: current-time
        uses: srfrnk/current-time@master
        with:
          format: X

      - name: Set branch name
        id: branch-name
        run: echo "::set-output name=result::$BRANCH_NAME"
        env:
          BRANCH_NAME: "update-end-${{ steps.current-time.outputs.formattedTime }}"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Create a new branch
        run: git checkout -b ${{ steps.branch-name.outputs.result }}

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Run bdh to update end date
        run: npx bangumi-data-helper end

      - name: Commit changes
        id: commit-changes
        uses: wxt2005/git-auto-commit-action@master
        with:
          commit_message: Update end date
          branch: ${{ steps.branch-name.outputs.result }}

      - name: Create pull request
        if: steps.commit-changes.outputs.changes_detected == 'true'
        run: |
          hub pull-request -m "Auto end date update" --no-edit -r $REVIEWER -a $REVIEWER
        env:
          REVIEWER: wxt2005
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
